version: "3.7"

volumes:
  lvreact_mysql:

networks:
  lvreact_net:
    driver: bridge

services:

  #app:
    #image: bitnami/laravel

  mysql_db:
    image: mysql
    volumes:
      - lvreact_mysql:/var/lib/mysql
    networks:
      - lvreact_net
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lvreact
