version: "3.7"

volumes:
  lvreact_mysql:

networks:
  lvreact_net:
    driver: bridge

services:

  frontend:
    build: ./frontend
    networks:
      - lvreact_net
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=http://localhost:8000
    depends_on:
      - backend

    backend:
      build: ./backend
      networks:
        - lvreact_net
      ports:
        - 8000:8000
      environment:
        - DB_CONNECTION=mysql
        - DB_HOST=database
        - DB_PORT=3306
        - DB_DATABASE=lvreact
        - DB_USERNAME=root
        - DB_PASSWORD=root
      depends_on:
        - database

      database:
        image: mysql
        volumes:
          - lvreact_mysql:/var/lib/mysql
          - ./db:/docker-entrypoint-initdb.d
        networks:
          - lvreact_net
        ports:
          - 3307:3306
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lvreact
